[Back port] Fix narrowing warnings
This is a backport from bowtie2
commit: c619b9ab47ea1da67bee7258353d0791120384f4 .

This causes an error with gcc 10 & aarch64, s390x, ppc64le.

alphabet.cpp:293:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]